[book]
authors = ["zjp"]
language = "en"
multilingual = false
src = "src"
title = "The Little Book of Rust Macros （Rust 宏之书）"


[build]
create-missing = true
build-dir = "book"

[output.html]
default-theme = "ayu"
site-url = "/tlborm/"
mathjax-support = true
git-repository-url = "https://github.com/zjp-CN/tlborm"
additional-css = ["res/rust-syntax-bg-highlight.css"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
