[book]
authors = ["Daniel Keep", "Veykril", "DaseinPhaos", "zjp"]
language = "zh"
multilingual = true
src = "src"
title = "The Little Book of Rust Macros （Rust 宏小册）"

[build]
create-missing = true
build-dir = "book"

#[preprocessor.toc]
#command = "mdbook-toc"
#renderer = ["html"]
#max-level = 4

[output.html]
default-theme = "ayu"
site-url = "/tlborm/"
mathjax-support = true
git-repository-url = "https://github.com/zjp-CN/tlborm"
additional-css = ["theme/rust-syntax-bg-highlight.css", "theme/style.css"]
additional-js = ["theme/sidebar.js"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false
